version: '3'
services:
 spark-master:
  image: bde2020/spark-master:3.1.1-hadoop3.2
  container_name: spark-master
  ports:
   - '8080:8080'
   - '7077:7077'
  environment:
   - INIT_DAEMON_STEP=setup_spark
  volumes:
   - ./codes:/home
 spark-worker-1:
  image: bde2020/spark-worker:3.1.1-hadoop3.2
  container_name: spark-worker-1
  depends_on:
   - spark-master
  ports:
   - '8081:8081'
  environment:
   - 'SPARK_MASTER=spark://spark-master:7077'
  volumes:
   - ./codes:/home
 # spark-worker-2:
 #   image: bde2020/spark-worker:3.1.1-hadoop3.2
 #   container_name: spark-worker-2
 #   depends_on:
 #     - spark-master
 #   ports:
 #     - "8082:8081"
 #   environment:
 #     - "SPARK_MASTER=spark://spark-master:7077"
 spark-jupyter:
  image: jupyter/pyspark-notebook
  container_name: spark-jupyter
  ports:
   - '4040-4050:4040-4050'
   - '8888:8888'
  volumes:
   - ./codes:/home/jovyan/work
